/**
 * Catálogo Lucide (datos IconNode) para Atic.
 * Importar desde aquí evita tirar del barrel completo en cada vista.
 */
import type { IconNode } from "morphicons/svelte";
import {
  AlignLeft,
  AppWindow,
  AudioLines,
  Activity,
  Calculator,
  Camera,
  CircleDot,
  Clipboard,
  Coffee,
  MemoryStick,
  Crop,
  FileImage,
  FileText,
  FileType,
  Folder,
  GraduationCap,
  Globe,
  GripVertical,
  History,
  Image,
  Info,
  Keyboard,
  Layers,
  Lightbulb,
  List,
  ListChecks,
  LoaderCircle,
  Lock,
  Mic,
  MousePointer2,
  Pencil,
  Pipette,
  Power,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShieldOff,
  ShieldMinus,
  SlidersHorizontal,
  SquareTerminal,
  Star,
  Trash2,
  Type,
  ArrowLeftRight,
  Plus,
  Share2,
  Minus,
  X,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Pin,
  Plug,
  Presentation,
  Copy,
  Sun,
  Moon,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ExternalLink,
  Check,
  SkipBack,
  SkipForward,
  ArrowLeft,
  ScanText,
  Monitor,
  SquareArrowOutUpRight,
  ArrowDownWideNarrow,
  Square,
  ArrowRight,
  ArrowUp,
  ChevronLeft,
  Cpu,
  House,
  Paperclip,
  Eraser,
  Circle,
  MoveUpRight,
  Undo2,
  Redo2,
  Highlighter,
  Save,
  Download,
  Ellipsis,
  EllipsisVertical,
  Pill,
  PanelRightClose,
  PanelRightOpen,
  PanelBottomOpen,
  PanelTopClose,
} from "lucide";
import type { ToolId } from "$lib/tools";

export type SettingsIconId =
  | "general"
  | "shortcuts"
  | "audio"
  | "summary"
  | "settings"
  | "about";

/**
 * Iconos que no son ni una herramienta ni una sección de ajustes.
 *
 * `more` es el gajo que abre el segundo anillo de la pill; `pill` la nombra en
 * la navegación de Ajustes; `window` abre la ventana principal desde «Más»;
 * `customize` abre el editor de la pill desde su tira.
 * Van aparte para que `ToolId` siga siendo la lista de herramientas y nada más:
 * sumarle «more» o «window» haría que el `switch` exhaustivo de `toolActions`
 * pidiera una acción para algo que no la tiene.
 */
export type ExtraIconId = "more" | "pill" | "back" | "window" | "customize";

export type AppIconId = ToolId | SettingsIconId | ExtraIconId;

export const TOOL_ICONS: Record<AppIconId, IconNode> = {
  meetings: CircleDot,
  dictation: Mic,
  agents: SquareTerminal,
  clipboard: Clipboard,
  snippets: AlignLeft,
  system: Cpu,
  captures: Crop,
  board: Pencil,
  color: Pipette,
  launcher: Search,
  general: Settings,
  settings: Settings,
  shortcuts: Keyboard,
  audio: AudioLines,
  summary: FileText,
  about: Info,
  more: Ellipsis,
  pill: Pill,
  back: ArrowLeft,
  window: AppWindow,
  customize: SlidersHorizontal,
};

export const LAUNCHER_ICONS: Record<string, IconNode> = {
  dictation: Mic,
  capture: Crop,
  board: Pencil,
  color: Pipette,
  clipboard: Clipboard,
  snippets: FileText,
  system: Cpu,
  agents: SquareTerminal,
  settings: Settings,
  calc: Calculator,
  "quit-all": Power,
  "sys-lock": Lock,
  "sys-sleep": Moon,
  "sys-mute": VolumeX,
  "sys-trash": Trash2,
  app: AppWindow,
  search: Search,
};

export const AGENT_ICONS = {
  "shield-manual": ShieldCheck,
  "shield-edits": Shield,
  "shield-plan": ShieldMinus,
  "shield-open": ShieldOff,
  folder: Folder,
  mic: Mic,
  clip: Clipboard,
  camera: Camera,
  mcp: Share2,
  history: History,
  read: FileText,
  edit: Pencil,
  delete: Trash2,
  move: Pencil,
  search: Search,
  execute: SquareTerminal,
  think: Lightbulb,
  fetch: Globe,
  switch_mode: ArrowLeftRight,
  other: Plus,
} as const satisfies Record<string, IconNode>;

export {
  Activity,
  Coffee,
  MemoryStick,
  Search,
  Trash2,
  List,
  Star,
  X,
  SlidersHorizontal,
  Minus,
  Plus,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Pin,
  Plug,
  Lock,
  Copy,
  Sun,
  Moon,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  Check,
  SkipBack,
  SkipForward,
  Mic,
  Settings,
  History,
  ArrowLeft,
  ScanText,
  Monitor,
  SquareArrowOutUpRight,
  ArrowDownWideNarrow,
  Square,
  ArrowRight,
  ArrowUp,
  ChevronLeft,
  ChevronRight,
  Folder,
  GraduationCap,
  Cpu,
  House,
  Paperclip,
  SquareTerminal,
  AppWindow,
  GripVertical,
  Pencil,
  Eraser,
  Circle,
  MoveUpRight,
  Undo2,
  Redo2,
  Highlighter,
  Save,
  Download,
  Camera,
  FileImage,
  FileText,
  FileType,
  Image as ImageIcon,
  Layers,
  LoaderCircle,
  PanelRightClose,
  Presentation,
  Ellipsis,
  EllipsisVertical,
  Pill,
  PanelRightOpen,
  PanelBottomOpen,
  PanelTopClose,
  Keyboard,
  Crop,
  Type,
  Pipette,
  MousePointer2,
  ListChecks,
};
