/**
 * Catálogo Lucide (datos IconNode) para Atic.
 * Importar desde aquí evita tirar del barrel completo en cada vista.
 */
import type { IconNode } from "morphicons/svelte";
import {
  AlignLeft,
  AppWindow,
  AudioLines,
  Camera,
  CircleDot,
  Clipboard,
  Crop,
  FileText,
  Folder,
  Globe,
  History,
  Keyboard,
  Lightbulb,
  List,
  Mic,
  Pencil,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShieldOff,
  ShieldMinus,
  SlidersHorizontal,
  SquareTerminal,
  Star,
  Trash2,
  ArrowLeftRight,
  Plus,
  Share2,
  Minus,
  X,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Pin,
  Copy,
  Sun,
  Moon,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  Check,
  SkipBack,
  SkipForward,
  ArrowLeft,
  ScanText,
  Monitor,
  SquareArrowOutUpRight,
  ArrowDownWideNarrow,
  Square,
  ArrowRight,
  ArrowUp,
  ChevronLeft,
  Cpu,
  House,
  Paperclip,
} from "lucide";
import type { ToolId } from "$lib/tools";

export type SettingsIconId =
  | "general"
  | "shortcuts"
  | "audio"
  | "summary"
  | "settings";

export type AppIconId = ToolId | SettingsIconId;

export const TOOL_ICONS: Record<AppIconId, IconNode> = {
  meetings: CircleDot,
  dictation: Mic,
  agents: SquareTerminal,
  clipboard: Clipboard,
  snippets: AlignLeft,
  captures: Crop,
  general: Settings,
  settings: Settings,
  shortcuts: Keyboard,
  audio: AudioLines,
  summary: FileText,
};

export const LAUNCHER_ICONS: Record<string, IconNode> = {
  dictation: Mic,
  capture: Crop,
  clipboard: Clipboard,
  snippets: FileText,
  agents: SquareTerminal,
  settings: Settings,
  app: AppWindow,
  search: Search,
};

export const AGENT_ICONS = {
  "shield-manual": ShieldCheck,
  "shield-edits": Shield,
  "shield-plan": ShieldMinus,
  "shield-open": ShieldOff,
  folder: Folder,
  mic: Mic,
  clip: Clipboard,
  camera: Camera,
  mcp: Share2,
  history: History,
  read: FileText,
  edit: Pencil,
  delete: Trash2,
  move: Pencil,
  search: Search,
  execute: SquareTerminal,
  think: Lightbulb,
  fetch: Globe,
  switch_mode: ArrowLeftRight,
  other: Plus,
} as const satisfies Record<string, IconNode>;

export {
  Search,
  Trash2,
  List,
  Star,
  X,
  SlidersHorizontal,
  Minus,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Pin,
  Copy,
  Sun,
  Moon,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  Check,
  SkipBack,
  SkipForward,
  Mic,
  Settings,
  History,
  ArrowLeft,
  ScanText,
  Monitor,
  SquareArrowOutUpRight,
  ArrowDownWideNarrow,
  Square,
  ArrowRight,
  ArrowUp,
  ChevronLeft,
  Folder,
  Cpu,
  House,
  Paperclip,
};
